name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - coiled-runtime=0.2.1
  - beautifulsoup4=4.11.1
  - matplotlib=3.6.2
  - pip
  - pip:
    - dask==2022.12.1
    - distributed==2022.12.1
