name: dask-tutorial-latest
channels:
  - conda-forge
dependencies:
  - python==3.10
  - dask==2023.5.0
  - distributed==2023.5.0
  - numpy==1.23.5
  - pandas==2.0.1
  - coiled==0.6.6
  - pyarrow==10.0.1
  - ipykernel==6.21.2
  - dask-labextension==6.1.0
  - jupyterlab==3.5.0
  - s3fs==2023.5.0
  - python-graphviz==0.20.1 
  - beautifulsoup4==4.11.1
  - matplotlib==3.6.2