name: dask-tutorial-lc
channels:
  - conda-forge
dependencies:
  - python==3.10
  - dask==2023.3.1
  - distributed==2023.3.1
  - numpy==1.23.5
  - pandas==1.5.3
  - coiled==0.5.17
  - pyarrow==10.0.1
  - ipykernel==6.21.2
  - dask-labextension==6.1.0
  - jupyterlab==3.5.0
  - s3fs==2023.3.0
  - python-graphviz==0.20.1 
  - beautifulsoup4==4.11.1
  - matplotlib==3.6.2
  - bokeh==2.4.3
