name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python==3.10
  - dask==2022.12.1
  - distributed==2022.12.1
  - numpy==1.23.5
  - pandas==1.5.2
  - coiled==0.2.59
  - pyarrow==10.0.1
  - ipykernel
  - dask-labextension==6.0
  - jupyterlab==3.5.0
  - s3fs==2022.11.0
  - python-graphviz
  - beautifulsoup4==4.11.1
  - matplotlib==3.6.2
  - bokeh==2.4.3
